spring.data.mongodb.uri=${MONGO_URL:mongodb://localhost:27017/dev}

spring.freemarker.suffix=.ftl

knote.minio.host=${MINIO_HOST:localhost}
knote.minio.port=${MINIO_PORT:9000}
knote.minio.bucket=${MINIO_BUCKET:image-storage}
knote.minio.access-key=${MINIO_ACCESS_KEY:${MINIO_ROOT_USER:mykey}}
knote.minio.secret-key=${MINIO_SECRET_KEY:${MINIO_ROOT_PASSWORD:mysecret}}
knote.minio.secure=${MINIO_SECURE:false}
knote.minio.reconnect-enabled=${MINIO_RECONNECT_ENABLED:true}
